apiVersion: v1
kind: Service
metadata:
  name: admin-web-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: admin-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8211
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-web
  template:
    metadata:
      labels:
        app: admin-web
    spec:
      containers:
        - name: admin-web
          image: <your-docker-user>/kub-cafe-admin:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
