apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-api
          image: <your-docker-user>/kub-cafe-order:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: 'mongodb://mongo-service:27017/cafe'
            - name: AUTH_ADDRESS
              value: 'auth-service:3000'
