services:
  mongo-service:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-api
    environment:
      TOKEN_KEY: 'doi-chuoi-nay-di'
      ADMIN_EMAIL: 'admin@cafe.local'
      ADMIN_PASSWORD: 'cafe1234'

  menu-service:
    build: ./menu-api
    environment:
      MONGODB_URI: 'mongodb://mongo-service:27017/cafe'
      AUTH_ADDRESS: 'auth-service:3000'
      MENU_IMAGE_FOLDER: '/app/data/images'
    volumes:
      - menu-images:/app/data/images

  order-service:
    build: ./order-api
    environment:
      MONGODB_URI: 'mongodb://mongo-service:27017/cafe'
      AUTH_ADDRESS: 'auth-service:3000'

  shop-web:
    build: ./shop-web
    ports:
      - '8210:80'

  admin-web:
    build: ./admin-web
    ports:
      - '8211:80'

volumes:
  mongo-data:
  menu-images:
