import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const sans = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "hautrank2 portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sans.className}>
      <body
        className={`antialiased dark bg-[url(/svg/bg-gr.svg)] bg-no-repeat bg-[-20vw_-80vh]`}
      >
        {children}
      </body>
    </html>
  );
}
